//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespoTesti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henkilot_bak
    {
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
        public string Sähköposti { get; set; }
        public string Puhelin { get; set; }
        public int Henkilö_ID { get; set; }
        public Nullable<int> Esimies { get; set; }
    }
}
