//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespoTesti.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoulukantaEntities : DbContext
    {
        public KoulukantaEntities()
            : base("name=KoulukantaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HENKILOT> HENKILOT { get; set; }
        public virtual DbSet<PROJEKTIT> PROJEKTIT { get; set; }
        public virtual DbSet<TUNNIT> TUNNIT { get; set; }
        public virtual DbSet<Henkilot_bak> Henkilot_bak { get; set; }
        public virtual DbSet<POSTITOIMIPAIKKA> POSTITOIMIPAIKKA { get; set; }
        public virtual DbSet<Tunnit2> Tunnit2 { get; set; }
    }
}
